name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/jod"

      - name: Install dependencies
        working-directory: src/back-end
        run: npm ci

      - name: Run tests
        working-directory: src/back-end
        run: npm run test
